project:
  type: website

website:
  title: "EkSabha - 4 curious"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/EkShunyam/EkSabha
      - icon: twitter
        href: https://twitter.com

format:
  html:
    theme: 
      light: sandstone
      dark: cyborg
    mainfont: Roboto
    css: styles.css
    toc: true



